# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://hxg10636.github.io/" # the url of your github pages

# site information used in page title, meta data etc.
title: "Xigang Huang Personal Website"
description: This is the websites for Xigang Huang

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Xigang Huang
author-bio: Data Analyst  # change to false to hide
author-image: IMG_3888.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Projects
  permalink: projects
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://www.instagram.com/denny970922/
github: https://github.com/hxg10636
linkedin: https://www.linkedin.com/in/xigang/
medium: false
google-scholar: false
email: huangxigang@gwu.edu

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
